version: '3.8'

services:
  employees:
    build: ./
    command: ./employees
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=qwerty

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./database:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:qwerty@db:5432/employees?sslmode=disable",
        "up",
      ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    restart: always
    image: postgres:latest
    ports:
      - 8001:5432
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: employees
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5